[[redirects]]
  from = "https://www.jeffreychiou.com/*"
  to = "https://www.jeffchiou.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://jeffreychiou.com/*"
  to = "https://www.jeffchiou.com/:splat"
  status = 301
  force = true

