[[redirects]]
  from = "https://www.jeffreychiou.com"
  to = "https://jeffchiou.com"
  status = 301
  force = true
  query = {path = ":path"}

[[redirects]]
  from = "https://jeffreychiou.com"
  to = "https://jeffchiou.com"
  status = 301
  force = true
  query = {path = ":path"}

